### ISSUE TITLE
Export requirements.txt

### ISSUE THREAD

**Issue by chaosWsF** [chaosWsF/Python-Toolkits#12]
#### Challenges
1. **Mixed Ecosystems**: GitHub’s Dependency Graph natively supports Pip (`requirements.txt`), but Conda (`environment.yml`) and system package managers (Homebrew, winget) aren’t fully integrated.
2. **ffmpeg Complexity**: As a non-Python dependency, `ffmpeg` isn’t tracked by Pip or Conda’s Python package lists—it’s a system binary with its own dependencies (e.g., codecs like `libx264`).
3. **Cross-Platform**: Homebrew (macOS) and winget (Windows) install `ffmpeg` differently, complicating reproducibility for dependents.
4. **Dependabot**: If enabled, it only updates Pip dependencies, not Conda, Homebrew, or winget packages.

---

#### Step 1: Document Python Dependencies

  - Conda + Pip Interaction
  - Merge Multiple Requirements

#### Step 2: Handle `ffmpeg` (Homebrew and winget)
Since `ffmpeg` is a system dependency installed via Homebrew and winget, it won’t appear in the Dependency Graph automatically. Here’s how to manage it:

1. **Manual Dependency Submission** (Optional):
   - Use GitHub’s **Dependency Submission API** to add `ffmpeg` to the Dependency Graph programmatically.
   - Create a GitHub Action to submit it:
     ```yaml
     # .github/workflows/dependency-submission.yml
     name: Submit Dependencies
     on:
       push:
         branches: [main]
     jobs:
       submit-dependencies:
         runs-on: ubuntu-latest
         steps:
           - uses: actions/checkout@v4
           - name: Submit ffmpeg dependency
             uses: github/dependency-submission-action@v3
             with:
               snapshot: |
                 {
                   "version": "0.1",
                   "job": {"correlator": "ffmpeg-submit"},
                   "sha": "${{ github.sha }}",
                   "dependencies": [
                     {
                       "package_url": "pkg:generic/ffmpeg@6.1",
                       "relationship": "direct",
                       "scope": "runtime"
                     }
                   ]
                 }
     ```
   - Adjust the version (`6.1`) to match your installed `ffmpeg`. This adds `ffmpeg` to the Dependency Graph under Insights.

2. **Document Installation Instructions**:
   - Since the graph won’t manage `ffmpeg` updates, document how to install it in your README:
     ```markdown
     ## Prerequisites
     - **ffmpeg**:
       - **macOS**: `brew install ffmpeg`
       - **Windows**: `winget install Gyan.FFmpeg`
     ```
   - Include version recommendations (e.g., `ffmpeg>=6.1`) to ensure compatibility with `yt-dlp`.

   - Commit and push:
     ```bash
     git add README.md
     git commit -m "Update README with ffmpeg prerequisites"
     git push
     ```

#### Step 3: Add Details to GitHub Wiki
Use your GitHub Wiki (`https://github.com/chaosWsF/Python-Toolkits/wiki`) for detailed setup or troubleshooting:

1. **Create a Setup Page**:
   - Go to your repo’s Wiki tab.
   - Create a new page (e.g., “Setup”).
   - Add:
     ```markdown
     # Setup Guide

     ## Python Environment
     - Install Python 3.11+.
     - Use `requirements.txt` for Python packages:
       ```bash
       pip install -r requirements.txt
       ```
     - This includes:
       - `flask`: Web framework.
       - `numpy`: Numerical operations.
       - `yt-dlp`: Video downloading.
       - `requests`: HTTP requests.

     ## System Prerequisites
     - **ffmpeg**: Essential for video processing in `video_scrapper`.
       - **macOS**:
         ```bash
         brew install ffmpeg
         ```
       - **Windows**:
         ```bash
         winget install Gyan.FFmpeg
         ```
       - Check version: `ffmpeg -version` (6.1+ recommended).

     ## Troubleshooting
     - If `yt-dlp` fails with "ffmpeg not found," ensure `ffmpeg` is in your PATH.

2. **Save and Publish**:
   - Click “Save Page” in the Wiki editor.

#### Step 4: Enhance Dependabot (Optional)
- Dependabot only updates `requirements.txt`. To monitor `ffmpeg`:
  - Use a GitHub Action to check `ffmpeg` versions periodically (Homebrew/winget don’t integrate with Dependabot directly).
  - Example Action:
    ```yaml
    # .github/workflows/check-ffmpeg.yml
    name: Check ffmpeg Version
    on:
      schedule:
        - cron: '0 0 * * 1' # Weekly on Monday
    jobs:
      check-ffmpeg:
        runs-on: ubuntu-latest
        steps:
          - name: Check Homebrew ffmpeg
            run: |
              brew update
              LATEST=$(brew info ffmpeg | grep -o 'stable [0-9.]*' | awk '{print $2}')
              echo "Latest ffmpeg (Homebrew): $LATEST"
          - name: Notify if outdated
            run: echo "Compare with your version (e.g., 6.1) and update README if needed."
    ```
  - This won’t auto-update `ffmpeg` but alerts you to manual updates.
  - **Dependabot**: Add a basic `dependabot.yml` to auto-update Pip packages:
    ```yaml
    # .github/dependabot.yml
    version: 2
    updates:
        - package-ecosystem: "pip"
        directory: "/"
        schedule:
            interval: "weekly"
    ```
  - Commit:
    ```bash
    git add .github/dependabot.yml
    git commit -m "Add Dependabot for requirements.txt"
    git push
    ```

**Comment by chaosWsF** [comment]
#### Conda + Pip Interaction
- When you run `pip freeze` in a Conda environment, it lists all Python packages installed in the environment’s `site-packages/` directory.
- **Conda-Installed Packages**: For packages installed via `conda install` (e.g., from `conda-forge`), Pip often can’t determine a clean version number because Conda uses its own build system. Instead, `pip freeze` outputs a file URI pointing to the Conda feedstock build artifact (e.g., `bidict @ file:///home/conda/...`).
- **Pip-Installed Packages**: Packages installed directly with `pip install` show standard `package==version` entries (e.g., `requests==2.32.3`).
- **Your Case**: Your environment likely has a mix of Conda-installed packages (showing file URIs) and Pip-installed ones (showing versions).

#### Example `requirements.txt`
```
bidict @ file:///home/conda/feedstock_root/build_artifacts/bidict_1734272627465/work
numpy @ file:///home/conda/feedstock_root/build_artifacts/numpy_1734181356789/work
requests==2.32.3
yt-dlp==2023.10.13
```

#### Dependabot Compatibility
- **Dependabot’s Behavior**: Dependabot parses `requirements.txt` to detect and update Python packages hosted on PyPI (the Python Package Index). It expects `package==version` syntax to match against PyPI’s version database.
- **File URIs**: Entries like `bidict @ file:///...` are **not compatible with Dependabot** because:
  - They’re local paths, not PyPI references.
  - Dependabot can’t resolve or update them, as it doesn’t access your local Conda build artifacts or Conda channels.
- **Result**: Dependabot will ignore these entries, only updating packages with explicit versions (e.g., `requests==2.32.3`).

### Solution: Script to Clean `requirements.txt`

Here’s a Python script to convert file URI entries to versioned entries: `clean_requirements.py`

#### Requirements
- Install `pyyaml`:
  ```bash
  pip install pyyaml
  ```

#### Caveat
- **Warnings**: If `bidict` is given as a different name in conda or pip file or it isn’t in `environment.yml`, you’ll see:
  ```
  Warning: No version found for bidict in environment.yml, keeping original: bidict @ file:///...
  ```
- **Conda vs. PyPI Versions**: Conda’s `bidict 0.23.1` might differ from PyPI’s (e.g., build optimizations). If `pip install bidict==0.23.1` fails or behaves differently, you’d need to test and possibly pin to PyPI-compatible versions manually.

### Final Workflow for Your Repo
1. **Export and Clean**:
   ```bash
   conda activate myenv
   conda env export > environment.yml
   pip freeze > requirements.txt
   python clean_requirements.py
   mv requirements_clean.txt requirements.txt
   ```
2. **Update README**:
   - Keep `ffmpeg` prerequisites separate (as planned).
   ```markdown
   ## Installation
   - Python: `pip install -r requirements.txt`
   - ffmpeg: 
     - macOS: `brew install ffmpeg`
     - Windows: `winget install Gyan.FFmpeg`
   ```
3. **Dependabot Config**:
   - Ensure `.github/dependabot.yml` is set:
     ```yaml
     version: 2
     updates:
       - package-ecosystem: "pip"
         directory: "/"
         schedule:
           interval: "weekly"
     ```
4. **Commit**:
   ```bash
   git add requirements.txt clean_requirements.py README.md
   git commit -m "Update requirements.txt for Dependabot and add cleaning script"
   git push
   ```
