### ISSUE TITLE
How to use Github?

### ISSUE THREAD

**Issue by chaosWsF** [chaosWsF/Python-Toolkits#2]
1. **Wiki**: GitHub’s wiki feature allows you to document your project, including setup instructions, usage guides, and known issues. For a media scraper, you might document how to configure environment variables for API keys, how to run the scraper, or notes on website structures. This is helpful for remembering details over time and could be useful if you decide to share the project later.

2. **GitHub Actions**: This feature automates workflows, such as running tests, building the project, or deploying it. For your scraper, you can set up actions to run unit tests on every push or pull request, ensuring code quality. Given your cross-platform setup, GitHub Actions supports runners for Windows, macOS, and Linux. For example, you can create a workflow file in `.github/workflows` to set up Python, run tests with `pytest`, and check for platform-specific issues. This is particularly beneficial for catching regressions early and ensuring compatibility, detailed at [GitHub Actions](https://docs.github.com/en/actions). For cross-platform, you can set up a workflow to test on `windows-latest` and `macos-latest` runners, catching any platform-specific bugs, such as differences in file paths or system calls. This is an unexpected benefit, as it leverages GitHub’s cloud infrastructure to simulate your local setups.

3. **Dependency Graph**: Your scraper likely depends on external libraries, such as `requests` for HTTP requests or `BeautifulSoup` for HTML parsing. The Dependency Graph visualizes these dependencies, showing versions, licenses, and potential vulnerabilities. This is crucial for maintaining security, especially for a project making web requests that could be exploited if dependencies have known issues. Enable it in repository settings under “Code security and analysis” and regularly check for updates.

4. **Security Features**: GitHub offers tools like code scanning, secret scanning, and dependency review to enhance project security. For a scraper, handling sensitive information like cookies or API keys is common, and these features help detect exposed secrets or vulnerabilities in code. Enable code scanning to automatically identify security issues, and use secret scanning to prevent accidental commits of sensitive data. This is vital for protecting your project, especially given the potential for web scraping to interact with sensitive systems, detailed at [Security Features](https://docs.github.com/en/code-security).

**Comment by chaosWsF** [comment]
For dependency graph, create a requirements.txt by pip freeze > requirements.txt

**Comment by chaosWsF** [comment]
## CI with GitHub Actions

### Step 1: Set Up Pytest
Here’s how to make `pytest` work in your repo:

#### 1. Add a Test Directory
Create a `tests/` folder in the root of your repo:
```
Python-Toolkits/
├── script1.py
├── script2.py
└── tests/
    └── test_something.py
```

#### 2. Write a Minimal Test
You don’t need tests for every file yet. Start with one test file to ensure `pytest` runs. For example, if `script1.py` has a function `add(a, b)`:
```python
# tests/test_something.py
from script1 import add

def test_add():
    assert add(2, 3) == 5
    assert add(-1, 1) == 0
```

- Name the file `test_*.py` or `*_test.py` so `pytest` finds it.
- Import the functions you want to test from your scripts.

#### 3. Install Pytest
Add `pytest` to your project:
- Create a `requirements.txt` if it doesn’t exist:
  ```
  pytest
  ```
- Or install locally with `pip install pytest` and commit the change.

#### 4. Configure Pytest (Optional)
Add a `pytest.ini` in the root to customize settings:
```ini
[pytest]
testpaths = tests
python_files = test_*.py *_test.py
```
This ensures `pytest` looks in `tests/` and follows your naming convention.

#### 5. Test Locally
Run `pytest` in your terminal from the repo root:
```bash
pytest
```
- If no tests exist: "No tests ran in 0.01s."
- If tests exist: It’ll run them and report pass/fail.

---

### Step 2: Add a CI Workflow
Now, let’s add a GitHub Actions CI workflow to run `pytest` automatically.

#### 1. Create the Workflow File
In your repo, create `.github/workflows/ci.yml`:
```yaml
name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x' # Adjust to your Python version (e.g., 3.11)

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          # Add other dependencies from requirements.txt if any
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run Tests
        run: pytest
```

#### 2. Commit and Push
```bash
git add .github/workflows/ci.yml tests/ requirements.txt pytest.ini
git commit -m "Add CI workflow with pytest"
git push origin main
```
Or create a PR if `main` is protected by your branch ruleset.

#### 3. Verify CI
- Go to your repo > **Actions** tab.
- See the "CI Pipeline" workflow run on push/PR. It’ll install `pytest`, run it, and report results.

---

### Step 3: Do You Need More Tests?
- **Minimal Approach**: One test file is enough to confirm `pytest` and CI work. Your workflow will pass even with no tests (exit code 0 if tests pass or none are found, 1 if tests fail).
- **Practical Approach**: Write tests for key scripts (e.g., ones with core logic or functions). You don’t need 100% coverage—focus on what matters (e.g., a utility function used across scripts).
- **Long-Term**: Gradually add tests as the repo grows. For a toolkit repo, test public-facing functions or scripts users rely on.

Example: If `script2.py` has a `process_data(data)` function, add:
```python
# tests/test_script2.py
from script2 import process_data

def test_process_data():
    assert process_data([1, 2, 3]) == expected_output
```

---

### Troubleshooting
- **Import Errors**: If `pytest` can’t import your scripts (e.g., `from script1 import add` fails), ensure your `.py` files are importable. Add an empty `__init__.py` in the root or adjust `PYTHONPATH`:
  ```yaml
  - name: Run Tests
    run: pytest
    env:
      PYTHONPATH: .
  ```
- **No Tests Found**: Ensure test files follow the naming convention and are in `tests/`.
- **CI Fails**: Check the Actions logs—common issues are missing dependencies or Python version mismatches.

---

## More

### Should You Use One YAML File or Multiple?
This depends on your project structure and goals. Here’s how to decide:

#### Option 1: Single YAML File
- **When to Use**:
  - Your repo is a single cohesive project (e.g., a Python app with some C++ extensions).
  - You want all CI logic in one place for simplicity.
  - Jobs (Python tests, C++ builds) can run sequentially or in parallel but don’t need separate triggers.
- **Pros**:
  - Easier to maintain initially.
  - One file to track all CI logic.
- **Cons**:
  - Can get bloated if you add many languages or platforms.
  - Harder to isolate failures if one part (e.g., C++) breaks but Python works.

Example single-file setup:
```yaml
name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  python-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - run: pip install pytest
      - run: pytest

  cpp-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-cpp@v1
        with: { cpp-version: '11' }
      - run: g++ -o myapp src/*.cpp
      - run: ./myapp --test
```

#### Option 2: Multiple YAML Files
- **When to Use**:
  - Your repo has distinct parts (e.g., a Python toolkit and a separate C++ library).
  - You want different triggers (e.g., Python tests on every push, C++ builds only on PRs).
  - You’re managing a monorepo with independent subprojects.
- **Pros**:
  - Cleaner separation of concerns.
  - Easier to debug or skip irrelevant workflows.
- **Cons**:
  - More files to manage.
  - Potential duplication (e.g., repeated checkout steps).

Example with two files:
- `.github/workflows/python-ci.yml`:
  ```yaml
  name: Python CI
  on: [push, pull_request]
  jobs:
    test:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-python@v5
          with: { python-version: '3.11' }
        - run: pip install pytest
        - run: pytest
  ```
- `.github/workflows/cpp-ci.yml`:
  ```yaml
  name: C++ CI
  on: [pull_request]
  jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-cpp@v1
          with: { cpp-version: '11' }
        - run: g++ -o myapp src/*.cpp
  ```

### How to Set Up CI for Your Mixed Needs
Here’s a practical single-file CI setup that covers Python, C/C++, and a cross-platform framework (e.g., Qt), with multi-platform testing:

```yaml
name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  python-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ['3.11']
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: pip install pytest
      - name: Run Tests
        run: pytest

  cpp-build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4
      - name: Install C++ Tools
        run: |
          if [ "${{ matrix.os }}" = "ubuntu-latest" ]; then sudo apt-get update && sudo apt-get install -y g++; fi
          if [ "${{ matrix.os }}" = "macos-latest" ]; then brew install gcc; fi
          # Windows uses MSVC by default, or install MinGW if preferred
      - name: Build C++
        run: g++ -o myapp src/*.cpp  # Adjust to your C++ files
      - name: Run C++ Tests
        run: ./myapp --test  # Add your test logic

  framework-build:
    runs-on: ubuntu-latest  # Example for Qt; adjust for your framework
    steps:
      - uses: actions/checkout@v4
      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: '6.5.0'
      - name: Build Project
        run: |
          qmake myproject.pro  # Your project file
          make
      - name: Run Tests
        run: ./myapp --test
```

---

### Key Considerations
1. **Cross-Platform Testing**:
   - Use a `matrix` strategy to test on Windows, macOS, and Linux, mimicking your dev environments (Windows 11, macOS M1) and broader deployment.
   - M1-specific quirks (e.g., ARM64) are handled by `macos-latest`, which supports Apple Silicon.

2. **Dependencies**:
   - Python: `pip install` works everywhere.
   - C/C++: Install compilers (`g++` on Linux/macOS, MSVC on Windows).
   - Frameworks: Install tools like Qt or Flutter via actions or package managers.

3. **Performance**:
   - C/C++ builds might take longer—cache dependencies to speed up:
     ```yaml
     - uses: actions/cache@v3
       with:
         path: ~/.cache/pip  # For Python
         key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
     ```

4. **Branch Ruleset**:
   - Tie this to your ruleset (e.g., require `python-tests`, `cpp-build` to pass before merging to `main`).
