### ISSUE TITLE
Set up Security

### ISSUE THREAD

**Issue by chaosWsF** [chaosWsF/Python-Toolkits#29]
### Dependabot

- If you want to keep updating your packages, you can use Dependabot. Dependabot is a GitHub app that checks for outdated dependencies in your repository and opens pull requests to update them.
- **Dependabot**: Add a basic `dependabot.yml` to auto-update Pip packages:
    ```yaml
    # .github/dependabot.yml
    version: 2
    updates:
      - package-ecosystem: "pip"
        directory: "/"
        schedule:
          interval: "monthly"
        version-updates: "security-only"
        open-pull-requests-limit: 5
        target-branch: "main"
    ```
- Commit:
    ```bash
    git add .github/dependabot.yml
    git commit -m "Add Dependabot for requirements.txt"
    git push
    ```

### Manual Dependency Submission (Optional):
  - Use GitHub’s **Dependency Submission API** to add `ffmpeg` to the Dependency Graph programmatically.
  - Create `ffmpeg_version.txt` in your repository with the current version, e.g.:
    ```
    6.0
    ```
  - Create a GitHub Action to submit it:
    ```yaml
    # .github/workflows/dependency-submission.yml
    name: Submit Dependencies
    on:
      push:
        branches: [main]
    jobs:
      submit-dependencies:
        if: github.event_name == 'push'
        runs-on: ${{ matrix.os }}
        strategy:
          matrix:
            os: [macos-latest, windows-latest]
        steps:
          - uses: actions/checkout@v4
          - name: Read FFmpeg version
            id: ffmpeg_version
            shell: bash # Force Bash on all OSes
            run: |
              VERSION=$(cat ffmpeg_version.txt)
              echo "VERSION=$VERSION" >> $GITHUB_ENV
          - name: Submit FFmpeg dependency snapshot
            shell: bash
            env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            run: |
              curl -L -X POST \
                -H "Accept: application/vnd.github+json" \
                -H "Authorization: Bearer $GITHUB_TOKEN" \
                -H "X-GitHub-Api-Version: 2022-11-28" \
                https://api.github.com/repos/${{ github.repository }}/dependency-graph/snapshots \
                -d '{
                  "version": 0,
                  "sha": "${{ github.sha }}",
                  "ref": "${{ github.ref }}",
                  "job": {
                    "correlator": "ffmpeg-submit",
                    "id": "${{ github.run_id }}"
                  },
                  "detector": {
                    "name": "custom-ffmpeg-detector",
                    "version": "0.0.1",
                    "url": "https://github.com/chaosWsF/Python-Toolkits"
                  },
                  "scanned": "'$(date -u +"%Y-%m-%dT%H:%M:%SZ")'",
                  "manifests": {
                    "ffmpeg": {
                      "name": "ffmpeg",
                      "file": {
                        "source_location": "ffmpeg_version.txt"
                      },
                      "resolved": {
                        "ffmpeg": {
                          "package_url": "pkg:generic/ffmpeg@${{ env.VERSION }}",
                          "relationship": "direct",
                          "scope": "runtime"
                        }
                      }
                    }
                  }
                }'
    ```
  - This adds `ffmpeg` to the Dependency Graph under Insights.

### Enhance Dependabot (Optional)
- Dependabot only updates `requirements.txt`. To monitor `ffmpeg`:
  - Use a GitHub Action to check `ffmpeg` versions periodically (Homebrew/winget don’t integrate with Dependabot directly).
  - Example Action:
    ```yaml
    # .github/workflows/check-ffmpeg.yml
    name: Check ffmpeg Version
    on:
      schedule:
        - cron: '0 0 * * 1' # Weekly on Monday
    jobs:
      check-ffmpeg-version:
        if: github.event_name == 'schedule'
        runs-on: ${{ matrix.os }}
        strategy:
          matrix:
            os: [macos-latest, windows-latest]
        steps:
          - uses: actions/checkout@v4
          - name: Read required FFmpeg version
            shell: bash
            id: required_version
            run: |
              REQUIRED=$(cat ffmpeg_version.txt)
              echo "REQUIRED=$REQUIRED" >> $GITHUB_ENV
          - name: Check FFmpeg version (macOS)
            if: matrix.os == 'macos-latest'
            run: |
              brew update
              LATEST=$(brew info ffmpeg | grep -o 'stable [0-9.]*' | awk '{print $2}')
              echo "Latest FFmpeg (Homebrew): $LATEST"
              echo "LATEST=$LATEST" >> $GITHUB_ENV
          - name: Install FFmpeg (Windows)
            if: matrix.os == 'windows-latest'
            run: |
              winget install -e --id Gyan.FFmpeg --silent
          - name: Check FFmpeg version (Windows)
            if: matrix.os == 'windows-latest'
            shell: pwsh
            run: |
              $INSTALLED = (ffmpeg -version | Select-Object -First 1).Split()[2]
              echo "INSTALLED=$INSTALLED" >> $env:GITHUB_ENV
              echo "Installed FFmpeg version (winget): $INSTALLED"
              echo "Required FFmpeg version: ${{ env.REQUIRED }}"
          - name: Create issue if outdated
            if: env.LATEST > env.REQUIRED
            uses: peter-evans/create-issue-from-file@v5
            with:
              title: "FFmpeg version outdated"
              content-filepath: .github/ISSUE_TEMPLATE/ffmpeg_update_template.md
              labels: "dependencies, ffmpeg"
    ```
  - The cron syntax in GitHub Actions follows the standard Unix format: `minute hour day_of_month month day_of_week`. Here’s what your current schedule means:
    - `0 0`: Midnight (00:00 UTC).
    - `* * 1`: Every Monday (`day_of_week = 1`).
  - This won’t auto-update `ffmpeg` but alerts you to manual updates.
  - Add a file at `.github/issue-template.md` with:
      ```markdown
      FFmpeg version is outdated!

      - Current required version: ${{ env.REQUIRED }}
      - Latest available version: ${{ env.LATEST }}

      Please update the FFmpeg version in the project.
      ```
